CREATE TABLE eg_category (
	id BIGINT NOT NULL,
	name CHARACTER VARYING(100) NOT NULL,
	description CHARACTER VARYING(250),
	active BOOLEAN NOT NULL,
	tenantId CHARACTER VARYING(250) NOT NULL,

	CONSTRAINT pk_eg_category PRIMARY KEY (id),
	CONSTRAINT uk_eg_category_name UNIQUE KEY (name)
);

CREATE SEQUENCE seq_eg_category INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;