CREATE TABLE eg_department (
	id BIGINT NOT NULL,
	name CHARACTER VARYING(64) NOT NULL,
	code CHARACTER VARYING(10) NOT NULL,
	active BOOLEAN NOT NULL,
	tenantId CHARACTER VARYING(250) NOT NULL,

	CONSTRAINT pk_eg_department PRIMARY KEY (id),
	CONSTRAINT uk_eg_department_code UNIQUE KEY (code),
	CONSTRAINT uk_eg_department_name UNIQUE KEY (name)
);

CREATE SEQUENCE seq_eg_department INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;