CREATE TABLE egeis_hrStatus (
	id BIGINT NOT NULL,
	objectName CHARACTER VARYING(50) NOT NULL,
	code CHARACTER VARYING(20) NOT NULL,
	description CHARACTER VARYING(250) NOT NULL,
	tenantId CHARACTER VARYING(250) NOT NULL,

	CONSTRAINT pk_egeis_hrStatus PRIMARY KEY (id)
);

CREATE SEQUENCE seq_egeis_hrStatus INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;